_target_: models.tokenizer.Tokenizer

# Modified according to the shape of the input images
vocab_size: 2048
embed_dim: 512
encoder:
  _target_: models.tokenizer.Encoder
  config:
    _target_: models.tokenizer.EncoderDecoderConfig
    resolution: 84
    in_channels: 1
    z_channels: 512
    ch: 64
    ch_mult: [1, 1, 1]
    num_res_blocks: 2
    attn_resolutions: [6, 12]
    out_ch: 1
    dropout: 0.0
decoder:
  _target_: models.tokenizer.Decoder
  config: ${..encoder.config}