defaults:
  - _self_
  - tokenizer: default
  - transformer: JOWA_150M
  - critic_head: JOWA_150M

initialization:
  path_to_checkpoint: null
  load_tokenizer: True
  load_world_model: True
  tokenizer_name: null
  world_model_name: JOWA_150M

common:
  game_name: Robotank  # BeamRider
  num_given_steps: 8  # 1~8
  device: "cuda:0"
  use_planning: False  # False  # True
  beam_width: 2
  horizon: 0
  num_eval_episodes: 1

  max_time: 10e10  # seconds
  max_steps: 108000
  seed: 0
  verbose: True
  dtype: bfloat16
  fps: 15
  header: False
  do_reconstruction: False
  save_mode: True
  save_rgb_img: True

hydra:
  run:
    dir: .
  output_subdir: null
