defaults:
  - _self_
  - tokenizer: default
  - transformer: JOWA_150M
  - critic_head: JOWA_150M

initialization:
  path_to_checkpoint: null
  load_tokenizer: True
  load_jowa_model: True
  tokenizer_name: null
  jowa_model_name: JOWA_150M

common:
  game_name: Assault
  num_given_steps: 8  # in [1,8]
  device: "cuda:0"
  use_planning: False
  beam_width: 1
  horizon: 0
  num_eval_episodes: 1
  use_mean: False
  use_count: False
  temperature: 1.0
  num_simulations: 20

  max_time: 10e10  # seconds
  max_steps: 108000
  seed: 0
  verbose: True
  dtype: bfloat16
  fps: 15
  header: False
  do_reconstruction: False
  save_mode: False
  save_rgb_img: True

action:
  vmin: -10
  vmax: 30
  num_atoms: 51
  td_loss: c51  # in [c51, mse]
  gamma: 0.99
  cql_weight: 0.1
  q_penalty: cql
  q_loss_backwards_wm: True
  use_task_embed: True

hydra:
  run:
    dir: .
  output_subdir: null
