defaults:
  - _self_
  - tokenizer: default

wandb:
  mode: online
  project: ScalingWorldModel
  entity: null
  name: null
  group: vqgan_multi_envs_4*4
  tags: null
  notes: null

initialization:
  path_to_checkpoint: null
  load_tokenizer: True

common:
  epochs: 200
  device: cuda
  do_checkpoint: True  # True to save optimizer
  seed: 0

training:
  should: True
  learning_rate: 0.0001
  world_size: 8
  log_interval: 50
  max_ckpts: 20
  tokenizer:
    dtype: bfloat16
    batch_num_samples: 512
    grad_acc_steps: 1
    max_grad_norm: 1.0
    
evaluation:
  should: True
  every: 1
  tokenizer:
    batch_num_samples: ${training.tokenizer.batch_num_samples}
    save_reconstructions: True

datasets:
  train:
    num_of_workers: 4
  test:
    num_of_workers: ${datasets.train.num_of_workers}

hydra:
  run:
    dir: .
  output_subdir: null