defaults:
  - _self_
  - tokenizer: default
  - world_model: default
  - actor_critic: default

wandb:
  mode: online
  project: ScalingWorldModelDLC
  entity: null
  name: ${common.group_name}_epoch_${common.epochs}_batch_size_${training.world_model.batch_num_samples}_wm_lr_${training.world_model.learning_rate}_critic_lr_${training.world_model.critic_lr}_supervise_weight_${actor_critic.supervised_weight}_cql_weight_${actor_critic.cql_weight}_num_q_head_${actor_critic.num_q}_embed_q_distribution
  group: wm_plus_critic_group_patch_6*6_params_40M_ablation  # tokenizer_plus_wm_group_patch_6*6  # wm_plus_critic_group_patch_6*6
  tags: null
  notes: null

initialization:
  load_tokenizer: outputs_shoot_vertical_group/world_model_plus_critic/2024-09-06/09-18-15/checkpoints/epoch_40  # outputs_group/world_model_plus_critic/2024-08-19/21-20-53/checkpoints/epoch_7  # outputs_group/tokenizer_plus_world_model/2024-08-15/13-12-45/checkpoints/epoch_8  # outputs_group/tokenizer_plus_world_model/2024-06-28/17-46-43/checkpoints/epoch_53  # outputs_group/world_model_plus_critic/2024-07-30/11-13-37/checkpoints/epoch_72  # outputs_group/tokenizer_plus_world_model/2024-06-28/17-46-43/checkpoints/epoch_53
  load_optimizer_tokenizer: False  # True  # False
  load_world_model: ${initialization.load_tokenizer}  # ${initialization.load_tokenizer}  # null
  load_optimizer_world_model: True  # True  # False
  load_start_epoch: True  # True  # False

common:
  envs: [Phoenix, Centipede, SpaceInvaders, Carnival, NameThisGame, Assault]
  group_name: shoot_vertical
  epochs: 200
  device: cuda
  do_checkpoint: True  # save optimizer
  seed: 0
  sequence_length: ${world_model.max_blocks}

training:
  should: True
  world_size: 8
  log_interval: 500
  max_ckpts: 100
  dtype: bfloat16
  tokenizer:
    should: False  # True  # False
    learning_rate: 0.00001
    batch_num_samples: 256
    max_grad_norm: 1.0
  world_model:
    learning_rate: 0.00005  # 0.00005  # 0.0001  # 0.00001
    train_critic: True  # False  # True
    critic_lr: 0.00005
    alpha_lr: 0.0
    batch_num_samples: 64  # 32
    max_grad_norm: 1.0
    weight_decay: 0.01
    imagine_horizon: ${common.sequence_length}

evaluation:
  should: True
  every: 1
  world_model:
    save_reconstructions: True  # True  # False
    critic_eval_step_frequency: 10e10  # ${actor_critic.target_update_frequency}  # 1000
    critic_eval_epoch_frequency: 1
  env:
    env_name: Assault  # SpaceInvaders  # Carnival
    num_eval_episodes: 1
    num_given_steps: 6
    max_time: 180  # seconds
    fps: 15
    header: False  # verbose info
    do_reconstruction: False  # save reconstruction images with original images
    save_mode: True  # save mp4 video

datasets:
  train:
    num_of_workers: 8

hydra:
  run:
    dir: .
  output_subdir: null