defaults:
  - _self_
  - tokenizer: default

wandb:
  mode: online
  project: ScalingWorldModelDLC
  entity: null
  name: ${common.group_name}_epoch_${common.epochs}_vocab_size_${tokenizer.vocab_size}
  group: vqgan_${common.group_name}_group_6*6
  tags: null
  notes: null

initialization:
  path_to_checkpoint: outputs_group/tokenizer_plus_world_model/2024-06-28/17-46-43/checkpoints/epoch_53
  load_tokenizer: True

common:
  envs: [Phoenix, Centipede, SpaceInvaders, Carnival, NameThisGame, Assault, Atlantis, DemonAttack, BeamRider, ChopperCommand, Seaquest, TimePilot, StarGunner, Berzerk, Zaxxon]
  group_name: shoot
  epochs: 2000
  device: cuda
  do_checkpoint: True  # True to save optimizer
  seed: 0

training:
  should: True
  learning_rate: 0.0001
  world_size: 8
  log_interval: 10
  max_ckpts: 5
  tokenizer:
    dtype: bfloat16
    batch_num_samples: 512
    grad_acc_steps: 1
    max_grad_norm: 1.0
    
evaluation:
  should: True
  every: 10
  tokenizer:
    batch_num_samples: ${training.tokenizer.batch_num_samples}
    save_reconstructions: True

datasets:
  train:
    num_of_workers: 4
  test:
    num_of_workers: ${datasets.train.num_of_workers}

hydra:
  run:
    dir: .
  output_subdir: null